### ISSUE TITLE
Latest vigraimpex does not compile with vtkhdf5 anymore

### ISSUE THREAD

**Issue by hmeine** [ukoethe/vigra#351]
VTK brings its own hdf5 library as a 3rdparty lib.  The library and symbol names are prefixed, which worked with vigra 1.10.0, but with the version-1-11-rc branch, I am now seeing compile errors with GCC in libvigraimpex:

    /usr/include/c++/5/functional:1436:53: error: ‘vtk__is_enum’ was not declared in this scope

These are obviously caused by VTK performing symbol mangling for libhdf5_hl by #defining all symbols exported by that DLL, adding `vtk__` prefixes in `${VTK_SOURCE}/vtkhdf5/vtk_libhdf5_hl_mangle.h` (for your convenience, see https://gitlab.kitware.com/vtk/vtk/blob/master/ThirdParty/hdf5/vtkhdf5/hl/src/vtk_libhdf5_hl_mangle.h ). Most of these symbols start with "H5", but a small percentage is not namespaced, and one of these symbols is `is_enum`, which is also used in `/usr/include/c++/{4.7,4.8,5}/{functional,type_traits}`.

This is not really an issue *of* vigra, but an issue *with* vigra, and although the problem clearly is VTK's implementation of the symbol mangling, it might affect enough vigra users that I thought I should bring it up here, too.  Maybe we can shuffle the `#include`s to work around this...

**Comment by ukoethe** [comment]
I'm not aware of any change in VIGRA that may have caused this change in behavior. Are you sure that the older VTK wasn't configured with `-DVTK_USE_SYSTEM_HDF5=ON`? That's what I would recommend anyway.

If you find a way to fix this in VIGRA and want to see it in 1.11, I need a pull request today.

**Comment by hmeine** [comment]
Yes, absolutely sure.  Our repository is build nightly on many platforms (think 6 to 16), and all dependencies are to be pulled from our ThirdParty repository, not from the system.  Yes, we could place hdf5 next to VTK, instead of re-using vtkhdf5 for vigra, that would be a clean solution.  The change in vigra may just be a new include, or a changed inclusion order.

**Comment by ukoethe** [comment]
So, will you send a fix today?

**Comment by hmeine** [comment]
No, I will not fix this for 1.11.  (I was operating on the trunk here, which caused bad things, so I would have to set up a separate branch and corresponding build job to try the fix without breaking things for all of my colleagues.)  Let's close this issue, I can still reference it if I find a workaround.
