### ISSUE TITLE
vigra master do not build on mac os x mountain lion

### ISSUE THREAD

**Issue by lfiaschi** [ukoethe/vigra#131]
Vigra master do not currently compile on mac os Mountain Lion 10.8 with Xcode 4 provided gcc (version 4.2 apple modified)

the error message ends at:

/Users/lfiaschi/phd/workspace/vigra-github/vigranumpy/src/core/accumulator.cxx:130:   instantiated from here
/Users/lfiaschi/phd/workspace/vigra-github/include/vigra/accumulator.hxx:2873: error: no matching function for call to ‘get(const vigra::CoupledHandlevigra::Multiband<float, vigra::CoupledHandle<vigra::TinyVector<long int, 3>, void> >&)’
make[2]: **\* [vigranumpy/src/core/CMakeFiles/vigranumpy_analysis.dir/accumulator.cxx.o] Error 1
make[1]: **\* [vigranumpy/src/core/CMakeFiles/vigranumpy_analysis.dir/all] Error 2
make: **\* [all] Error 2
