### ISSUE TITLE
Issue using bind<int>(size_t) in combination with templates

### ISSUE THREAD

**Issue by emmenlau** [ukoethe/vigra#457]
I think the following should be legal code but it does not build with gcc-7.3.0 on Ubuntu 18.04 and not with XCode 9 on MacOSX 10.13:
```
template <class T>
void BindError(const vigra::MultiArray<3, T>& aTypeDed, const vigra::MultiArray<3, double>& aDouble) {
    // This fails to compile:
    MultiArrayView <2, T> array1 = aTypeDed.bind<2>(11);
}

int main() {
    vigra::MultiArray<3, double> aWorkImages(vigra::Shape3(128, 128, 128));
    BindError(aWorkImages,aWorkImages);
}
```

See also #456 for the corresponding build error

**Comment by emmenlau** [comment]
Example build error on Linux:
```
2018-11-06T09:10:01.1542048Z [ 48%] Building CXX object test/multiarray/CMakeFiles/test_multiarray.dir/test.cxx.o
2018-11-06T09:10:03.2447152Z /home/vsts/work/1/s/test/multiarray/test.cxx: In instantiation of ‘void BindError(const vigra::MultiArray<3, T>&, const vigra::MultiArray<3, double>&) [with T = double; typename vigra::detail::ResolveMultiband<T>::type = double]’:
2018-11-06T09:10:03.2448573Z /home/vsts/work/1/s/test/multiarray/test.cxx:191:18:   required from ‘void MultiArrayDataTest<T>::test_bindT() [with T = int]’
2018-11-06T09:10:03.2448871Z /home/vsts/work/1/s/test/multiarray/test.cxx:3121:18:   required from here
2018-11-06T09:10:03.2449370Z /home/vsts/work/1/s/test/multiarray/test.cxx:65:49: error: invalid operands of types ‘<unresolved overloaded function type>’ and ‘int’ to binary ‘operator<’
2018-11-06T09:10:03.2449646Z      MultiArrayView <2, T> array1 = aTypeDed.bind<2>(11);
2018-11-06T09:10:03.2449835Z                                     ~~~~~~~~~~~~~^~
2018-11-06T09:10:03.2450447Z /home/vsts/work/1/s/test/multiarray/test.cxx:65:27: warning: unused variable ‘array1’ [-Wunused-variable]
2018-11-06T09:10:03.2450747Z      MultiArrayView <2, T> array1 = aTypeDed.bind<2>(11);
2018-11-06T09:10:03.2451166Z                            ^~~~~~
2018-11-06T09:10:04.6509488Z test/multiarray/CMakeFiles/test_multiarray.dir/build.make:62: recipe for target 'test/multiarray/CMakeFiles/test_multiarray.dir/test.cxx.o' failed
2018-11-06T09:10:04.6512002Z make[3]: *** [test/multiarray/CMakeFiles/test_multiarray.dir/test.cxx.o] Error 1
2018-11-06T09:10:04.6512817Z CMakeFiles/Makefile2:2789: recipe for target 'test/multiarray/CMakeFiles/test_multiarray.dir/all' failed
2018-11-06T09:10:04.6513031Z make[2]: *** [test/multiarray/CMakeFiles/test_multiarray.dir/all] Error 2
2018-11-06T09:10:04.6513424Z CMakeFiles/Makefile2:278: recipe for target 'CMakeFiles/check.dir/rule' failed
2018-11-06T09:10:04.6513636Z make[1]: *** [CMakeFiles/check.dir/rule] Error 2
2018-11-06T09:10:04.6515265Z Makefile:236: recipe for target 'check' failed
2018-11-06T09:10:04.6515462Z make: *** [check] Error 2
```
